name: "Build Documentation"

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'Sources/**'
      - 'Package.swift'
  pull_request:
    paths:
      - '.github/workflows/docs.yml'
      - 'Sources/**'
      - 'Package.swift'
  workflow_dispatch:

permissions:
  packages: read

env:
  XCODE_VERSION: "Xcode_26.0" # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md

jobs:
  build:
    name: "Build Documentation"
    runs-on: macos-26
    steps:
      - name: "Checkout Source"
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #pin v6.0.1
        with:
          persist-credentials: false

      - name: "Prepare Build Environment"
        id: prepare
        run: |
          echo "Switching to ${{ env.XCODE_VERSION }}"
          sudo xcode-select -s /Applications/${{ env.XCODE_VERSION }}.app/Contents/Developer
          xcode-select -p
          xcode-select -p

      - name: "Compile Documentation"
        id: compile_docs
        run: |
          swift package add-dependency "https://github.com/apple/swift-docc-plugin" --revision 3e4f133a77e644a5812911a0513aeb7288b07d06
          swift package --allow-writing-to-directory docs generate-documentation --target DNSKit --disable-indexing --output-path docs --transform-for-static-hosting
          tar -cf docs.tar docs/
          rm -rf docs/

      - name: "Archive Documentation"
        id: archive_docs
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #pin v5.0.0
        with:
          name: docs
          path: docs.tar
